# Generated by Django 3.2.8 on 2022-10-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_leader',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vpm',
        ),
        migrations.AddField(
            model_name='vpm',
            name='leader_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='车队领头'),
        ),
        migrations.AddField(
            model_name='vpm',
            name='member',
            field=models.ManyToManyField(to='nav.Car', verbose_name='成员'),
        ),
    ]
