# Generated by Django 3.2.8 on 2022-10-08 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_auto_20221007_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpm',
            name='leader_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='车队领头车ID'),
        ),
        migrations.AlterField(
            model_name='vpm',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, to='nav.Car', verbose_name='成员'),
        ),
        migrations.CreateModel(
            name='NavigationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_pos', models.CharField(max_length=32, verbose_name='当前位置')),
                ('target_pos', models.CharField(max_length=32, verbose_name='目标位置')),
                ('status', models.IntegerField(choices=[(0, '导航中'), (1, '导航完成')], default=0, verbose_name='导航状态')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nav.car', verbose_name='导航任务绑定车辆')),
                ('vpm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nav.vpm', verbose_name='导航任务绑定车队')),
            ],
        ),
    ]
