# Generated by Django 3.2.8 on 2022-10-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0003_auto_20221008_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpm',
            name='member',
            field=models.ManyToManyField(blank=True, to='nav.Car', verbose_name='成员'),
        ),
    ]
