# Generated by Django 3.2.8 on 2022-10-08 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0004_alter_vpm_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationtask',
            options={'ordering': ['-add_time'], 'verbose_name': '导航任务', 'verbose_name_plural': '导航任务'},
        ),
        migrations.AddField(
            model_name='navigationtask',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='加入时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navigationtask',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
