# Generated by Django 3.2.8 on 2022-10-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0005_auto_20221008_1251'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='navigationtask',
            unique_together={('car', 'vpm')},
        ),
    ]
