# Generated by Django 3.2.8 on 2022-10-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0006_alter_navigationtask_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpm',
            name='sn',
            field=models.CharField(max_length=32, verbose_name='车队编号'),
        ),
        migrations.AlterUniqueTogether(
            name='vpm',
            unique_together={('name', 'sn')},
        ),
    ]
